speed(0)
penup()
square_length = int(input("What is the square's side length?: "))
setposition(-200,-200)
pendown()
def draw_square():
    for i in range(4):
        forward(square_length)
        left(90)
draw_square()
penup()
forward(400 - square_length)
pendown()
draw_square()
penup()
forward(square_length)
left(90)
forward(400 - square_length)
pendown()
draw_square()
penup()
forward(square_length)
left(90)
forward(400 - square_length)
pendown()
draw_square()