speed(10)
penup()
setposition(-100,-100)
pendown()
radius = int(input("What is the radius?: "))
def draw_square(color_choice,radius):
    color(color_choice)
    begin_fill()
    for i in range(4):
        forward(radius*2)
        left(90)
    end_fill()
draw_square("red",radius)
penup()
forward(radius)
color("blue")
pendown()
begin_fill()
circle(radius)
end_fill()