happy = input("Are you happy?: ")
speed(10)
def draw_smiley():
    penup()
    color("yellow")
    setposition(0,-100)
    pendown()
    begin_fill()
    circle(100)
    end_fill()
    penup()
    left(90)
    forward(35)
    right(90)
    color("black")
    pensize(5)
    pendown()
    circle(65,-90)
    circle(65,180)
    penup()
    setposition(40,40)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    left(90)
    forward(75)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
if happy == "yes":
    draw_smiley()