happy = input("how are you feeling ? ")
speed(10)
penup()
color("yellow")
setposition(0,-100)
pendown()
begin_fill()
circle(100)
end_fill()
penup()
left(90)
forward(35)
right(90)
color("black")
pensize(5)
def draw_smile():
    pendown()
    circle(65,-90)
    circle(65,180)
    penup()
    setposition(40,40)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    left(90)
    forward(75)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
def draw_frown():
    setposition(0,0)
    left(180)
    pendown()
    circle(65,90)
    circle(65,-180)
    penup()
    setposition(40,40)
    pendown()
    begin_fill()
    circle(5)
    end_fill()
    penup()
    left(90)
    forward(75)
    pendown()
    begin_fill()
    circle(5)
    end_fill()

if happy == "happy":
    draw_smile()
elif happy == "sad":
    draw_frown()