speed(0)
def purple_circle():
    penup()
    forward(100)
    color("purple")
    begin_fill()
    circle(10)
    end_fill()
    penup()
    backward(100)
def blue_circle():
    penup()
    forward(100)
    color("blue")
    begin_fill()
    circle(10)
    end_fill()
    penup()
    backward(100)
def red_circle():
    penup()
    forward(100)
    color("red")
    begin_fill()
    circle(10)
    end_fill()
    penup()
    backward(100)
for i in range(12):
    purple_circle()
    left(10)
    blue_circle()
    left(10)
    red_circle()
    left(10)