speed(0)
penup()
def red_square():
    setposition(-100,50)
    pendown()
    color("red")
    pendown()
    begin_fill()
    circle(60,360,4)
    end_fill()
    penup()
def blue_circle():
    setposition(100,50)
    pendown()
    color("blue")
    pendown()
    begin_fill()
    circle(60)
    end_fill()
    penup()
def yellow_semicircle():
    setposition(-125,-125)
    pendown()
    color("yellow")
    begin_fill()
    circle(60,180)
    end_fill()
    penup()
def green_pentagon():
    setposition(100,-125)
    pendown()
    right(180)
    color("green")
    begin_fill()
    circle(60,360,5)
    end_fill()
    penup()
red_square()
blue_circle()
yellow_semicircle()
green_pentagon()